
\documentclass[12pt]{article}

\usepackage{authblk}
\usepackage{tabularx}
\usepackage{float}
\usepackage{amsmath}
\usepackage{longtable}
\usepackage[margin=1in]{geometry}
\usepackage[font=sf]{caption}

% Latex special characters are rendered correctly with XeTeX
\usepackage{xltxtra}
\usepackage{xunicode}
\defaultfontfeatures{Mapping=tex-text}

% Words are cut where needed
\usepackage{polyglossia}
\setdefaultlanguage[variant=american]{english}

% Use fancy fonts
\usepackage{fontspec}
\setmainfont[Ligatures=TeX]{Crimson Text}
\setsansfont{SourceSansPro-Regular}

% tables
\usepackage{multirow}

\newcolumntype{b}{X}
\newcolumntype{s}{>{\hsize=.2\hsize}X}

\title{Barcoding in sea cucumbers}

\author[1]{Fran\c{c}ois Michonneau\thanks{francois.michonneau@gmail.com}}
\author[1]{Gustav Paulay\thanks{paulay@flmnh.ufl.edu}}

\affil[1]{Florida Museum of Natural History, University of Florida, Gainesville,
  FL 32611-7800, USA}

\renewcommand\Authands{ and }

% -------- end of header --------- %

\begin{document}

<<setup, echo=FALSE, cache=FALSE, include=FALSE>>=
opts_chunk$set(fig.path="figures/latex-", cache.path="cache/latex-", dev="tikz",
                external=TRUE, fig.width=6.5, fig.height=4, fig.align="center")
options(tikzDefaultEngine = "xetex")
options(tikzDocumentDeclaration = paste(getOption("tikzDocumentDeclaration"),
            "\n\\renewcommand*{\\familydefault}{\\sfdefault}", sep=""))
read_chunk("code/cuke-barcoding.R")
source("R/load.R")
@

<<load-packages, echo=FALSE, cache=FALSE, include=FALSE>>=
@

\maketitle

% Main message (less than 25 words):

% There is a large amount of unrecognized diversity among Echinoderms.
% This diversity is mostly generated in allopatry, but rapid secondary sympatry is
% rampant. (23 words)

\begin{abstract}
  Estimates for the number of species in the sea vary by orders of
  magnitude. Molecular taxonomy can greatly speed up screening for diversity and
  evaluating species boundaries.  DNA barcoding with a region of cytochrome
  oxidase 1 (COI) is now widely used as a first pass for molecular evaluation of
  diversity, as it has good potential for identifying cryptic species and
  improve our understanding of marine biodiversity. We present the results of a
  large scale barcoding effort for echinoderms, focusing here on asteroids,
  echinoids and holothuroids. We sequenced over 3,900 individuals from numerous
  localities across the Indo-Pacific and the Caribbean. Many species show
  genetic differentiation between ocean basins, and some are even differentiated
  among archipelagos. The number of cryptic species is much higher than
  currently recognized. The vast majority of sister species have allopatric
  distributions. However, many closely related and sympatric forms which exhibit
  distinct color patterns and/or ecology show little differentiation in and
  cannot be separated by COI sequence. This pattern is much more common among
  echinoderms than among molluscs or arthropods. This suggests that echinoderms
  acquire reproductive isolation at a much faster pace than other marine
  phyla. Understanding the causes behind such pattern will refine our
  understanding of diversification and biodiversity among echinoderms.
\end{abstract}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Figures

%% graph that shows # of lineages vs. threshold used
%%  - use different color lines for the methods
%%  - bPTP, GMYC, distance threshold, LBGM
%%  - include barplot in background that shows proportion of nodes supported by
%%  high BS for each method
%%  - do the graph for all species, and break down by Orders

%% Maps of the geographical distribution of the samples

%% barplot that shows number of
%% - named species
%% - ESUs
%% - ESUs represented by 1 sequence

%% scatterplot of:
%% - % divergence between cluster vs. abs(latitude)
%% - intraspp variation vs abs(latitude)

%% barplot that shows taxonomic coverage of the sampling
%% use different colors for each taxonomic group and shade to represent
%% percentage covered by samples



\section{Introduction}

Barcoding studies have typically two main goals: species discovery (how does the
barcoding data compare to the taxonomy?), and specimen identification (can the
barcode library be used to identify a species?) \cite{Collins2013}. In this
study we focus on describing the patterns of unrecognized diversity, and testing
the role of latitude and phylogeny in shaping these patterns.

% introduce idea of barcoding gap

* barcoding has limitations, but when used with comprehensive taxonomic and
geographic sampling, powerful to assess diversity, in particular in groups that
haven't received lots of taxonomic attention

* In such cases, barcoding has typically revealed more diversity than previously
acknowledged. From the variety of studies, clearly many different patterns
emerge. Using large datasets allow to evaluate the relative importance of these
patterns. Examples: differentiation between IO and PO, unrecognized endemics in
Red Sea, Hawaii

* On the other hand, barcoding has also revealed instances of clear
morphological differences with limited genetic differentiation. Three main
hypotheses to explain this pattern (hybridization, incomplete lineage sorting,
polymorphism). How common is this pattern? Are the same explanations always
behind these patterns?

* few groups have been sampled extensively. Diversity in IWP thought to follow
diversity patterns of more well-known species: mollusks, fish, corals. Most of
the diversity is in the coral triangle. However, other groups don't always seem
to follow this pattern (e.g., Calcinus). Comprehensive sampling allows to
revisit this question.

* Behind these patterns is rate of secondary sympatry, molecular data allows to
test whether diversification occurs mostly in allopatry or in sympatry. And
once, diversification has occurred how long it takes for species to co-exist in
sympatry.

* To assess time it takes, need a good molecular clock, however, in most marine
invertebrates not really possible because fossils are too limited. However,
there are several pairs of sister species across isthmus of Panama, so we can
evaluate differences in rates, and

* This study is on sea cucumbers because poor understanding of species limits
use of conservative characters used in species-level taxonomy. Yet need for
management and better understanding of biology given fisheries pressures.

* Presentation of the dataset: most geographically and taxonomically
comprehensive barcoding dataset.

* Goals:
  - assess amount of cryptic diversity
  - evaluate geographic patterns of diversity and diversification
  - re-evaluate molecular clock


\section{Materials and Methods}

\subsection{Sampling}

Specimens were collected on snorkel, on SCUBA, or by dredging. Most were
photographed while alive \textit{in situ} or in the lab anesthetized in a 1:1
solution of sea water and 7.5\% solution of magnesium chloride hexahydrate, then
preserved in 75\% ethanol. When possible tentacles were clipped, immediately put
in 95-99\% ethanol, and later used for DNA extractions.  Specimens were
deposited in the Invertebrate Zoology collections of the Florida Museum of
Natural History, University of Florida (UF), Gainesville, FL, USA, while tissue
samples are stored in the Genetic Resources Repository of this museum.

Additional samples were obtained through collaborators either from newly
collected material or from preserved specimens deposited in other institutions.

\Sexpr{dim(load_cukeAlg())[1]} individuals were identified and sequenced. They
represent the worldwide diversity of sea cucumbers, with a particular focus on
the species of the Indo-Pacific and the Antarctic regions
(Fig.\ref{fig:sampling}). The northern hemisphere and deep-water species outside
of the Antarctic region are under-represented.

<<sampling-maps, cache=TRUE, echo=FALSE, warning=FALSE, fig.height=6, fig.cap='Locations sampled in this study'>>=

@


\subsection{Specimen identification}

Most specimens were individually identified by GP, FM, Mark O'Loughlin and other
taxonomic specialists. For most groups, survey of primary literature was used to
assign the most accurate names. This effort led to the re-discovery of taxonomic
names that have been forgotten/never used in the literature, and names were
resurrected from synonymies.

\subsection{Sequencing}

DNA was extracted according to one of the following three protocols: (1) DNAzol
followed by QIAGEN PCR clean up kit; (2) organic extractions at the Smithsonian
Institution using robotic facilities; (3) EZNA Mollusc kit. In each case, the
manufacturer's protocol were used.

We amplified the 5' end (655~base pairs) of the mitochondrial gene COI using the
echinoderm primers developed by \cite{Hoareau2010}. The sequencing was performed
at the Interdisciplinary Center Biotechnology Research at the University of
Florida. Chromatograms were assembled and edited using Geneious 5.5.8
\cite{Geneious558}.

We kept all sequences that were more than 600 bp and that did not include any
stop or non-sense codons that may have resulted from incorrect base calling
during the sequencing or the editing process.

Sequences were aligned with MAFFT

\subsection{Diversity}

% context: How much diversity in a group that hasn't received lots of
% taxonomic attention and with potential for high levels of cryptic diversity
% because of characters used to delineate species? and yet, relatively easy to
% sample

In this study we use the term Evolutionary Significant Unit (ESU) to designate
individuals that differ by species-level genetic differentiation and could
potentially represent reproductively isolated lineages. Typically, this
definition implies that these individuals also differ in another independent
distinguishing characteristic such as a morphological trait or divergence in an
independent genetic locus (\textit{sensu} \cite{Moritz1994}). Here, many of the
ESUs identified differ morphologically, but it was not always possible to assess
these differences owing to the few individuals available. In other cases, no
obvious differences were detected but they may be characterized by subtle
differences in their ossicle assemblages that have not been investigated
thoroughly.

The size of the dataset restricts the methods that can be used to assess
diversity, as computationally intensive methods such as the Generalized Mixed
Yule Coalescent method \cite{Pons2006} cannot be used here. Other programs
cannot accommodate such large dataset, and failed to complete the analysis
(e.g. PTP \cite{Zhang2013}, AGBD \cite{Puillandre2012a}). Therefore, we were
limited to use threshold-based methods to estimate the number of ESUs and used
two approaches: pairwise distances and the cluster identification method.

Based on pairwise distances, we grouped individuals that diverged at most by a
given threshold. This method is strictly based on the genetic distance and does
not take into account phylogenetic information.

We also used here a new method that identifies monophyletic clusters of
individuals from a neighbor-joining tree (other tree reconstruction methods can
be used), reconstructed from the pairwise genetic distances. Individuals
belonging to the same cluster are separated by genetic distance less than a
threshold set \textit{a priori}. Since it is based on the maximum intraspecific
distance, it shares similarity with the local barcoding graphs, where maximum
intra-specific distance between individuals is plotted against the distance to
the closest neighboring species (see \cite[Fig.~4 in]{Robinson2009} for an
example). It differs as it only uses information from the tree (no need to
associate species names with the sequences), but suffers from the caveats
associated with using arbitrary thresholds.

% This method is less conservative
% compared to the pairwise distance method since individuals with divergent
% haplotypes will be considered to belong to different ESUs if theythat differ

For each of these two approaches, we used both uncorrected distances ($p$) and
the Kimura two-parameter (K2P) distance \cite{Kimura1980} to estimate pairwise
distances. The K2P distance is very widely used in barcoding studies, but a
recent study indicated that the $p$ distance is probably more appropriate when
comparing genetic distances between closely related species and may lead to
higher rates of identification success \cite{Collins2012}. We estimated the
number of species recovered from our sample while varying the pairwise threshold
value: \Sexpr{paste0(load_thresholdPairwise(), collapse=", ")}. Additionally, we
estimated the proportion of singletons (proportion of the number species
represented by a single individual) for each of these threshold values. If a
suitable threshold allows the detection of the barcoding gap, we expect the
number of estimated ESUs to not drop as abruptly once the threshold passes is
high enough to capture the range of intra-ESU genetic variability and groups
together diverging individuals. Similarly, we expect that the proportion of
singletons stops decreasing when the threshold is high enough that it captures
individuals with slightly divergent haplotypes. We repeated these analyses on
the entire dataset, on each order, and each family to assess if different
thresholds were needed for various taxonomic groups.

It has been suggested previously that using a threshold equals to 10 times the
intraspecific distance \cite{Hebert2004a} for pairwise distance was
appropriate. However, this approach was not suitable in our study as the high
levels of cryptic species were considerably inflating the apparent levels of
intraspecific distances.

\subsection{Geography, diversity and diversification}

\subsubsection{Patterns of diversity}

% - [future] map of number of unique haplotypes per geographic areas
% - [future] use different colors to code species mostly in the Pacific, mostly in IO or
% both so we can dissect if the pattern of diversity is caused by the same
% species or not

We investigated the geographic patterns of diversity from the ESUs identified
from the barcoding data. For each ESU, when three or more locations were
sampled, we computed the convex hull to obtain a polygon approximating their
geographic distributions. We superimposed these polygons to obtain a diversity
contour map.

\subsubsection{Isolation-by-distance}

<<isolation-by-distance-data, cache=TRUE, results='hide', echo=FALSE, warning=FALSE>>=
@

<<isolation-by-distance-stats, cache=TRUE, dependson='isolation-by-distance-data', echo=FALSE, results='asis'>>=
@

If dispersal is spatially restricted, a pattern of isolation-by-distance (IBD),
where genetic differentiation increases with geographical distance, may be
detected. In sea cucumbers, as with other marine invertebrate, dispersal
typically occurs during the larval stage. Larvae can be planktotrophic (they
feed in the plankton), or oligotrophic (they feed on reserves included with the
egg). A few species of sea cucumbers are also brooders, and adults release
juveniles. The type of development and larvae may influence the dispersal
potential of the species, with brooders having little dispersal potential while
species with planktotrophic larvae might disperse over longer distances. To test
for evidence of IBD we investigated the relationship between the maximum
intra-ESU genetic distances and the maximum geographical distances sampled for
each ESUs represented by three or more individuals. While the reproductive
biology of most sea cucumber species has not been investigated, it is recognized
that most species of Aspidochirotida and Apodida have planktotrophic larvae,
while species of Dendrochirotida have oligotrophic larvae. To assess if these
differences in life history among the orders had an effect of the IBD pattern,
we performed an analysis of covariance (ANCOVA) on the maximum genetic distance
for each species as the response variable, the maximum geographic distance as
the covariate, and the taxonomic order as the independent variable. We performed
the analysis on \Sexpr{paste(orderToInclude, collapse=', ')}.
The variances among the orders were homogeneous (Levene's test,
\Sexpr{leveneIbdFstat}, \Sexpr{leveneIbdP}).

% To test whether tropical and low-latitude species affected the IBD
% pattern, we performed an ANCOVA on the maximum intra-ESU genetic distances as
% the response variable, the maximum geographical distance for each ESU as the
% covariate and the zone of occurrence as the independent variable (species for
% which the absolute mean of their latitudinal range is < 23$^{\circ}$ were
% classified as ``tropical'', others were classified as ``other''). We only had
% enough data for the Dendrochirotida to do this analysis. For the other groups,
% we compared the results obtained on the full dataset and on the dataset
% restricted to the zone of occurrence with the most data (tropics for the
% Aspidochirotida and Apodida; other for the Elasipodida). We did not have enough
% data to analyze the Molpadida or the Dactylochirotida separately.

\subsubsection{Geography of diversification}

If speciation occurs in allopatry, recently diverged species may retain
allopatric distributions. To investigate the geographic distributions of
recently diverged ESUs, we tested whether sister ESUs were sympatric or
allopatric. We identified sister ESUs based on the neighbor-joining tree
estimated from the uncorrected distances. If the distributions of the ESUs
could be inferred with a polygon, we classified their distributions as:
parapatric if less than 10\% of the range of the ESU with the smallest range
overlapped with the species with the larger range, sympatric is their ranges
overlapped by more than 10\%, and allopatric otherwise. If only one species had
enough data to estimate its distribution with a polygon, and points were
available for the other species, we considered their distribution allopatric if
none of the points were included in the polygon, and sympatric if they were.

To investigate the relative contributions of geographic barriers to the
formations of ESUs within the Indo-Pacific, we recorded the approximate
boundaries separating allopatric sister ESUs.


% - Diversification:
%   - [X] Are sister species allopatric or sympatric?
%   - [X] role of geologic/geographic barriers / Where are the barriers to cladogenesis?
%   - [future] Is there signal that the timing of differentiation is similar for areas
%   with high endemism? Hawaii? Red Sea?
%   - [future] Rates of secondary sympatry
%   - amount of divergence among individuals found in sympatry
%       (plot: %divergence vs. %sympatry(smaller ranged species))


% \subsection{Molecular clock estimation}

% - can we use isthmus of panama to calibrate the sea cucumber molecular clocks?
% - differences in pairwise divergence for geminate species caused by:
% - differences in timing: some species might have diverged before closure of
% isthmus
% - differences in rates of molecular evolution

\section{Results}

\subsection{Diversity}

<<n-species, cache=TRUE, echo=FALSE>>=

@

<<cluster-groups-data, cache=TRUE, echo=FALSE>>=

@

<<pairwise-groups-data, cache=TRUE, echo=FALSE>>=

@

<<groups-comparison-plot, dependson=c('pairwise-groups-data', 'cluster-groups-data', 'n-species'), cache=TRUE, echo=FALSE, fig.height=6.5, fig.cap='Comparison of the number of ESUs (top), and the proportion of ESUs represented by a single individual (singletons, bottom) estimated with the pairwise distance method (pairwise) and the clustering method (cluster), based on uncorrected distances (uncorrected) or the Kimura 2-parameter distances (K2P), for the entire dataset (all), the order Aspidochirotida and the family Holothuriidae. The gray horizontal dashed line represents the number of named species sequenced.', fig.scap='Estimated number of ESUs'>>=

@

<<stats-groups, dependson=c('n-species', 'groups-comparison-plot'), cache=TRUE, echo=FALSE>>=
spPair003 <- load_species_pairwiseGrps("K80", "all", 0.03)
spCluster004 <- load_species_clusterGrps("K80", "all", 0.02)
pCrypticAll <- c(nSppAll/length(spPair003), nSppAll/length(spCluster004))
@

<<mean-intra-named-species, cache=TRUE, dependson='n-species', echo=FALSE>>=

@


% - [results] show image that represent: differences in topologies,
% (paraphyly/polyphyly), long branches
% - [results] adequate sampling across the range of the species

Among the \Sexpr{dim(cukeAlg)[1]} individuals sequenced, we identified
\Sexpr{nSppAll} species. All orders of sea cucumbers were represented. The order
Aspidochirotida, and in particular the family Holothuriidae were the most
exhaustively sampled (\Sexpr{formatC(100*nSppAsp/nSppAll, width=2, format="d")}
and \Sexpr{formatC(100*nSppHol/nSppAll, width=2, format="d")} of the total number
of individuals respectively), with all genera and subgenera of the Holothuriidae
represented, and 65\% for the currently accepted species names.

On the entire dataset, regardless of the method or the distance threshold used,
the number of estimated ESUs was greater than the number of named species
suggesting cryptic diversity . The pairwise distance method led to lower
estimates than the clustering method and was less sensitive to the type of
distance used (Fig.~\ref{fig:groups-comparison-plot}). At the order level, and
for the Holothuriidae, the estimated number of ESUs plateaued for thresholds >
4\% with the clustering method and for thresholds > 2\% with the pairwise
distance method.

When all sequences where analyzed, the proportion of singletons varied between
35\% and 40\% for distance thresholds > 2\% for the pairwise method and for
thresholds > 4\% for the clustering method
(Fig.~\ref{fig:groups-comparison-plot}). Typically, these thresholds were more
variable when analyzing each orders individually (3\% and 5\% for both the
Aspidochirotida and the Holothuriidae, 3\% and 2.5\% for the Apodida, 3\% and
3\% for the Dendrochirotida, 2\% and 4\% for the Elasipodida.)

For the rest of the study we use the ESUs as delineated by the clustering method
with a threshold of 4\% based on the raw distances. This threshold provided a
compromise by separating ESUs with different color patterns or ecology, without
splitting ESUs that showed some level of geographic structure across their
range. This distance threshold also corresponds to the level where all methods
tested provided similar estimates of the proportion of singletons. We also
favored this approach as it led to reciprocally monophyletic groups that
facilitated the investigation of geographic patterns of diversity and
diversification.

With this threshold, the number of estimated ESUs is
\Sexpr{length(load_species_clusterGrps("raw", "all", 0.02))}. The difference
with the number of named species comes from species complexes. These complexes
can be deeply divergent populations across the range of species previously
thought to be circum-tropical. For instance, \textit{Holothuria arenicola} forms
a complex with different ESUs in the Caribbean basin, the Eastern Pacific and
the rest of the Indo-Pacific. For this species and others (e.g.,
\textit{Holothuria hilla}), these divergent lineages have overlapping ranges,
which made their recognition as distinct evolutionary units
challenging. Additionally, many species thought to occur in both Indian and
Pacific Oceans (e.g., \textit{Holothuria pervicax}, \textit{Holothuria
  fuscocinerea}), or to reach peripheral areas of the Indo-Pacific (e.g.,
\textit{Holothuria cinerascens} has ESUs both in Hawaii and the Red Sea), appear
highly divergent genetically, sometimes accompanied with morphological
differences.

Our large scale sampling effort also led to the discovery of ESUs that appear to
be undescribed species. These include large, commercially important species. For
the Holothuriidae that have been the most comprehensively sampled, 12 ESUs
clearly differentiated morphologically, are potentially new species not directly
part of a species complex.

For some groups that were sampled extensively, we recovered less ESUs than there
are described species. Notably, in \textit{Opheodesoma}, that currently include
11 species, we only recovered 4 ESUs as well as 2 probably undescribed species.

In a few cases, groups of individuals that appear morphologically differentiated
were grouped together in an ESU. This was in particular the case of
\textit{Holothuria edulis} which harbors two color morphs: gray  and fuschia;
and several species in \textit{Stichopus}. One the other hand, there were some
cases of species that were split into several ESUs but that did not seem to be
differentiated morphologically and that had broadly overlapping ranges.


% Typically, the recommended threshold in barcoding studies is 10 times the
% average intraspecific distance \cite{Hebert2004a} when using the pairwise
% method. The intraspecific distance for the overall dataset was
% \Sexpr{formatC(mean(meanIntraSppAll, na.rm=TRUE)*100, digits=2)}\%
% (N=\Sexpr{formatC(sum(!is.na(meanIntraSppAll)))}),
% \Sexpr{formatC(mean(meanIntraSppAsp, na.rm=TRUE)*100, digits=2)}\% for the
% Aspidochirotida (N=\Sexpr{formatC(sum(!is.na(meanIntraSppAsp)))}),
% \Sexpr{formatC(mean(meanIntraSppDen, na.rm=TRUE)*100, digits=2)}\% for the
% Dendrochirotida (N=\Sexpr{formatC(sum(!is.na(meanIntraSppDen)))}),
% \Sexpr{formatC(mean(meanIntraSppApo, na.rm=TRUE)*100, digits=2)}\%
% (N=\Sexpr{formatC(sum(!is.na(meanIntraSppApo)))}) for the Apodida,
% \Sexpr{formatC(mean(meanIntraSppEla, na.rm=TRUE)*100, digits=2)}\%
% (N=\Sexpr{formatC(sum(!is.na(meanIntraSppEla)))}) for the Elasipodida,
% \Sexpr{formatC(mean(meanIntraSppMol, na.rm=TRUE)*100, digits=2)}\%
% (N=\Sexpr{formatC(sum(!is.na(meanIntraSppMol)))}) for the Molpadida. The 3\%
% thres


<<sampled-species, results='asis', echo=FALSE, cache=TRUE, dependson='n-species'>>=

@


\subsection{Geography, diversity and diversification}


\subsubsection{Patterns of diversity}

<<global-diversity-map, cache=TRUE, results='hide', echo=FALSE>>=
@

\begin{figure}
\begin{centering}
\includegraphics{figures/diversity-map}
\caption{Overlay of the polygons representing the distributions of all ESUs
  delineated with the clustering method with a threshold of 4\%, occurring
  between -30$^{\circ}$ and 30$^{\circ}$. The shade of red indicate the number
  of species co-occuring. The maximum number of overlapping ranges occurs
  North of Papua New Guinea with \Sexpr{sum(nSppPNG)} ESUs. }
\label{fig:diversity-map}
\end{centering}
\end{figure}


The highest diversity occurs in the Western Pacific with a maximum of
\Sexpr{sum(nSppPNG)} ESUs North East of New Guinea. Overall, diversity is
relatively consistent across the Indo-Pacific with about at least 25 ESUs
co-occurring from Madagascar to Hawaii, and from Taiwan to French
Polynesia. Diversity in the Indo-Malay archipelago is comparable to, or lower than
in other parts of the range with few ESUs restricted to this geographic area
(Philippines: \Sexpr{sum(nSppPhil)} ESUs, French Polynesia:
\Sexpr{sum(nSppPoly)} ESUs, Madagascar: \Sexpr{sum(nSppMada)} ESUs, Ryukyus:
\Sexpr{sum(nSppOki)} ESUs).


\subsubsection{Isolation-by-distance}

<<isolation-by-distance-plot, cache=TRUE, results='hide', echo=FALSE, warning=FALSE, dependson='isolation-by-distance-data', results='hide', fig.scap='Genetic and geographic distances for each order', fig.cap='Maximum genetic distance and maximum geographic distance for ESUs identified with the clustering approach with a threshold of 4\\%, represented by at least 3 individuals. Dashed lines represent the model estimated by an ANCOVA using the order as the independent variable.'>>=
@


<<ibd-text-stats, cache=TRUE, dependson='isolation-by-distance-data', echo=FALSE>>=
tmpDendro <- subset(distBySpecies, Order == "Dendrochirotida")
maxDistDendro <- tmpDendro[which.max(tmpDendro$maxGeoDist), ]
gMaxDistDendro <- round(maxDistDendro$maxGeoDist, 0)
genMaxDistDendro <- maxDistDendro$maxGenDist
meanRange <- with(subset(distBySpecies, latCat == "tropical"),
                  tapply(maxGeoDist, Order, mean))
sdRange <- with(subset(distBySpecies, latCat == "tropical"),
                tapply(maxGeoDist, Order, sd))
@

<<isolation-by-distance-table, cache=TRUE, results='asis', echo=FALSE, dependson='isolation-by-distance-stats'>>=
@

The ANCOVA testing for the effect of maximum geographic distance and ``order''
on the maximum genetic distance was significant (\Sexpr{ancovaFstat},
\Sexpr{ancovaP}). Neither the interaction between ``order'' and geographic
distance (\Sexpr{interactionFstat}, \Sexpr{interactionP}), nor the ``order''
terms (\Sexpr{interceptFstat}) were significant, indicating a common slope and a
common intercept for the orders included in the analysis
(Table~\ref{tab:ibd-stats}).

We recovered a signal of isolation-by-distance (IBD) for Apodida,
Aspidochirotida and Dendrochirotida (Fig.~\ref{fig:isolation-by-distance-plot},
Table~\ref{tab:ibd-stats}). Typically, ESUs that spanned the entire range of the
Indo-Pacific had higher genetic distances than species with restricted
ranges. However, there was a considerable amount of variation and a number of
species with large ranges were characterized by low genetic differences. For
instance, one of the ESUs among the Dendrochirotida, \textit{Afrocucumis
  africana}, a small species with leicthotrophic development \cite{Chao1995},
that occurs from the Western Indian Ocean to the Western Pacific Ocean (maximum
distance: \Sexpr{formatC(gMaxDistDendro, format="d")}~km) was characterized by a
maximum intra-ESU distance of \Sexpr{round(genMaxDistDendro, 3)}\%.

For the tropical species, the means of the maximum distances for the Apodida
(\Sexpr{round(meanRange["Apodida"],2)}~km, SD= \Sexpr{round(sdRange["Apodida"],
  2)}) and the Aspidochirotida (\Sexpr{round(meanRange["Aspidochirotida"], 2)}~km,
SD=\Sexpr{round(sdRange["Aspidochirotida"], 2)}) were larger than for the
Dendrochirotida (\Sexpr{round(meanRange["Dendrochirotida"], 2)}~km,
SD=\Sexpr{round(sdRange["Dendrochirotida"], 2)}).

\subsubsection{Geography of diversification}

<<geography-diversification, cache=TRUE, echo=FALSE, fig.width=5, fig.height=3, fig.scap='Geography of diversification', fig.cap='Number of geographic types for ESU pairs identified by the clustering method with a 4\\% threshold'>>=

@

We compared the geographic ranges of \Sexpr{sum(complete.cases(spComp))} pairs
of sister ESUs. Most had allopatric distributions (\Sexpr{formatC(percentAllo,
  digits=2, width=2)}\%), the other sister ESUs were sympatric
(\Sexpr{formatC(percentSymp, digits=2, width=2)}\%), and or parapatric
(\Sexpr{formatC(percentSymp, digits=2, width=2)},
Fig.~\ref{fig:geography-diversification}).


\begin{figure}
\begin{centering}
\includegraphics{figures/map-barriers}
\caption[Geographical barriers separating ESUs]{Approximate locations of the
  geographical barriers separating sister ESUs. Numbers indicate number of
  sister ESUs separated by the barrier. Pink lines indicate barriers separating
  3 sister ESUs. Dashed orange lines indicate barriers separating 1 sister ESU.}
\label{fig:map-barriers}
\end{centering}
\end{figure}

In the Indo-Pacific, most allopatric ESUs were separated by the Arabian Sea (7
pairs of sister ESUs), the Western Indian Ocean (7 pairs), the Indo-Malay
archipelago (5 pairs) or the Timor Sea (4 pairs). Other significant barriers
were in the Central Pacific with endemic lineages to the Hawaiian archipelago,
or sister species across the Easter Pacific barrier
(Fig.~\ref{fig:map-barriers}).


\section{Discussion}

%% Neutrality of the sequences?
% Are all protein sequences identical?

\subsection{Diversity}

This study reveals that the sea cucumber taxonomy does not reflect the diversity
in this group. Regardless of the method used to estimate ESUs from the genetic
data, we recovered more species than we could identify based on accepted
taxonomic names.

As with all threshold-based method, in particular, over such taxonomic and
latitudinal breadths, a single measure does not fully capture the range of
evolutionary mechanisms and historical processes that have generated the
patterns of diversity observed. The species that deviate from the common pattern
can however provide insights into the biology of these species.

% TODO -- make figures to illustrate these cases
The single threshold used led to some cases of discordance between groups of
individuals that were differentiated morphologically and groups that were
differentiated genetically. In some cases, ESUs grouped individuals
morphologically distinct (e.g., \textit{Holothuria edulis}), sometimes described
as different species (e.g., \textit{Bohadschia atra} and \textit{Bohadschia
  argus}). This pattern could result from (1) recently diverged species that
harbor genetic differentiation inferior to the threshold used, (2)
introgression, (3) morphological polymorphism that is not indicative of species
limits. The concordance of reciprocal monophyly and morphological
differentiation in most cases suggest recent divergence. This is also the case
for \textit{Holothuria edulis} where one ESU only includes individuals of the
gray morph, while the other includes both the gray and the fuschia morphs,
suggestive of incomplete lineage sorting. We detected a suspected instance of
hybridization between two species of the genus \textit{Bohadschia}
\cite{Kim2013}.

The low interspecific genetic distance leading to the lumping of different
species within a single ESU could also be the result of a slower molecular
clock. In the absence of fossil evidence, the closure of the isthmus of Panama
is the only reliable geological event that can be used to calibrate the
molecular clock. A few sister species are found on each sides of the isthmus and
their divergence might be associated with the closure of the isthmus. However,
there are challenges associated with estimating the time of divergence of these
sister species. The closure of the isthmus was a gradual process that was fully
completed about 2.8 million years ago (My), but some species might have
initiated their divergences earlier, and might have been fully reproductively
isolated before the final closure \cite{Lessios2008}. Additionally,
trans-isthmian species might not be sister, as the most closely related species
might occur elsewhere, leading to an overestimation of the molecular clock
rate. We limited the likelihood of comparing the wrong species pairs through
extensive sampling. For instance, in the ``\textit{Holothuria impatiens}''
complex we found that the species most closely related to the species from the
Caribbean occurs in the Galapagos, and is not the one occurring in the Eastern
Pacific coast. Finally, even with equal mutation rates, and simultaneous
divergences, differences in levels of ancestral polymorphism will lead to
variation in the time to the most common recent ancestor \cite{Hickerson2006,
  Hurt2009}. Thorough analyses of the most likely hypotheses explaining the
range of pairwise differences observed across the isthmus (from 1.9\% to 14.5\%)
will be needed. However, it is interesting to note that the sister species with
the lowest rates (\textit{Euapta lappa} and \textit{Euapta godeffroyi}) belong
to the family where the threshold approach led to fewer species than what is
currently recognized in the taxonomy: \textit{E. lappa} and
\textit{E. godeffroyi} were grouped together as a single ESU despite being
separated by the isthmus; \textit{Opheodesoma} counts 11 species but we
recovered only 2 ESUs (and 2 ESUs that corresponded to undescribed species);
\textit{Synaptula} counts 30 species but we recovered 8 ESUs. Members of these
genera are variable morphologically, and many of these species were described on
the basis of a single specimen, suggesting that at least some of these names
will need to be synonymized. For \textit{Opheodesoma}, which we investigated in
more detail, we did not find any clear association between the morphological
types and the ESUs, and the broad geographical overlap of in their distributions
suggest that they may not be reproductively isolated.

These exceptions were however rare, and most species formed reciprocally
monophyletic groups that matched one or more of the ESUs delineated with the
threshold method. Funk and Ormland \cite{Funk2003} estimated that 23\% of the
2,319 animal species they surveyed were non-monophyletic in their mitochondrial
genealogies. In the Holothuriidae, for which we investigated morphological
differences more thoroughly, we recovered a much lower rate of 2\% (4 out of
\Sexpr{length(load_species_clusterGrps("raw", "Holothuriidae",
  0.02))}~ESUs). The rapid coalescence of the mitochondrial lineages could stem
from low effective population sizes associated with the life history
characteristics of marine invertebrates (e.g., fluctuations in population sizes,
unequal contributions to the reproductive pool). The original dataset from Funk
and Ormland did not include many invertebrates.

Since most species are monophyletic, it makes sea cucumbers a great target for
species level identification through barcoding as unknown sequences will cluster
unambiguously with the correct species is the vast majority of the cases.

%% explain low variation but not rapid coalesence, does it?
%A recent study proposes the importance of selective sweeps

% - [discussion] does it really matter that ESUs identified aren't really species?
% they are proxy for genetic diversity --> much higher than current understanding
% of species limits


\subsection{Geography, diversity and diversification}

The highest diversity in sea cucumbers is not the coral triangle but the Western
Pacific.

The polygon approach used to identify areas of high diversity has
limitations. In particular, it may overestimate diversity where species do not
occur but occur at the periphery. Some species included in our analysis have
restricted ranges or are known from a single specimen, and no polygons were
drawn for them. Therefore the diversity from the polygons is underestimated. For
instance, 65 species have been recorded for Guam \cite{Michonneau2013}, but
\Sexpr{sum(nSppGuam)} ESUs are estimated from the polygons.

<<ibd-text-stats-discuss, cache=TRUE, dependson='isolation-by-distance-data', echo=FALSE>>=
maxRangeElasi <- max(subset(distBySpecies, Order == "Elasipodida")$maxGeoDist)
maxRangeElasiF <- formatC(round(maxRangeElasi, 0), format="d")
restrictAspido <- lm(maxGenDist ~ maxGeoDist, data=distBySpecies,
                     subset=(Order == "Aspidochirotida" & maxGeoDist < maxRangeElasi))
restrictDendro <- lm(maxGenDist ~ maxGeoDist, data=distBySpecies,
                     subset=(Order == "Dendrochirotida" & maxGeoDist < maxRangeElasi))
restrictApod <- lm(maxGenDist ~ maxGeoDist, data=distBySpecies,
                     subset=(Order == "Apodida" & maxGeoDist < maxRangeElasi))
@

By far, most sister ESUs were found in allopatry indicating the strong
influecnce that

species being sympatric:
- second rapid sympatry; other hypotheses e.g. Stichopus
- masking recent diversifications in it that are allopatric
- differences in rates of evolution Euapta
- double check pardalis
-

diversity of patterns in the Indian Ocean
displacement of Red Sea by expansion of Pacific Ocean species


% tradeoff between many species 1 gene / multiple genes

%% Geographical scale
% see Bergsten+2012





\pagebreak

\bibliographystyle{plos2009}
\bibliography{cuke-barcoding_nourl}

\pagebreak

\section{Supplementary material}
 a
<<sm-groups-comparison-plot, cache=TRUE, echo=FALSE, dependson='groups-comparison-plot', fig.height=6.5, fig.cap='Comparison of the number of ESUs (top), and the proportion of ESUs represented by a single individual (singletons, bottom) estimated with the pairwise distance method (pairwise) and the clustering method (cluster), based on uncorrected distances (uncorrected) or the Kimura 2-parameter distances (K2P), for the orders Apodida, Dendrochirotida and Elasipodida. The gray horizontal dashed line represents the number of named species sequenced.', fig.scap='Estimated number of ESUs'>>=

@


\end{document}

%% Diversification rates

%% Role of geography/latitude
% diversification rates
% intra- and interspecific genetic variation
