
\documentclass[12pt]{article}

\usepackage{authblk}
\usepackage{tabularx}
\usepackage{float}
\usepackage{amsmath}
\usepackage{longtable}
\usepackage[margin=1in]{geometry}
\usepackage[font=sf]{caption}

% Latex special characters are rendered correctly with XeTeX
\usepackage{xltxtra}
\usepackage{xunicode}
\defaultfontfeatures{Mapping=tex-text}

% Words are cut where needed
\usepackage{polyglossia}
\setdefaultlanguage[variant=american]{english}

% Use fancy fonts
\usepackage{fontspec}
\setmainfont[Ligatures=TeX]{Crimson Text}
\setsansfont{SourceSansPro-Regular}

% tables
\usepackage{multirow}

\newcolumntype{b}{X}
\newcolumntype{s}{>{\hsize=.2\hsize}X}

\title{Barcoding in sea cucumbers}

\author[1]{Fran\c{c}ois Michonneau\thanks{francois.michonneau@gmail.com}}
\author[1]{Gustav Paulay\thanks{paulay@flmnh.ufl.edu}}

\affil[1]{Florida Museum of Natural History, University of Florida, Gainesville,
  FL 32611-7800, USA}

\renewcommand\Authands{ and }

% -------- end of header --------- %

\begin{document}

<<setup, echo=FALSE, cache=FALSE, include=FALSE>>=
opts_chunk$set(fig.path="figures/latex-", cache.path="cache/latex-", dev="tikz",
                external=TRUE, fig.width=6.5, fig.height=4, fig.align="center")
options(tikzDefaultEngine = "xetex")
options(tikzDocumentDeclaration = paste(getOption("tikzDocumentDeclaration"),
            "\n\\renewcommand*{\\familydefault}{\\sfdefault}", sep=""))
read_chunk("code/cuke-barcoding.R")
source("R/load.R")
@

<<load-packages, echo=FALSE, cache=FALSE, include=FALSE>>=
@

\maketitle

% Main message (less than 25 words):

% There is a large amount of unrecognized diversity among Echinoderms.
% This diversity is mostly generated in allopatry, but rapid secondary sympatry is
% rampant. (23 words)

\begin{abstract}
  Estimates for the number of species in the sea vary by orders of
  magnitude. Molecular taxonomy can greatly speed up screening for diversity and
  evaluating species boundaries.  DNA barcoding with a region of cytochrome
  oxidase 1 (COI) is now widely used as a first pass for molecular evaluation of
  diversity, as it has good potential for identifying cryptic species and
  improve our understanding of marine biodiversity. We present the results of a
  large scale barcoding effort for echinoderms, focusing here on asteroids,
  echinoids and holothuroids. We sequenced over 3,900 individuals from numerous
  localities across the Indo-Pacific and the Caribbean. Many species show
  genetic differentiation between ocean basins, and some are even differentiated
  among archipelagos. The number of cryptic species is much higher than
  currently recognized. The vast majority of sister species have allopatric
  distributions. However, many closely related and sympatric forms which exhibit
  distinct color patterns and/or ecology show little differentiation in and
  cannot be separated by COI sequence. This pattern is much more common among
  echinoderms than among molluscs or arthropods. This suggests that echinoderms
  acquire reproductive isolation at a much faster pace than other marine
  phyla. Understanding the causes behind such pattern will refine our
  understanding of diversification and biodiversity among echinoderms.
\end{abstract}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Figures

%% graph that shows # of lineages vs. threshold used
%%  - use different color lines for the methods
%%  - bPTP, GMYC, distance threshold, LBGM
%%  - include barplot in background that shows proportion of nodes supported by
%%  high BS for each method
%%  - do the graph for all species, and break down by Orders

%% Maps of the geographical distribution of the samples

%% barplot that shows number of
%% - named species
%% - ESUs
%% - ESUs represented by 1 sequence

%% scatterplot of:
%% - % divergence between cluster vs. abs(latitude)
%% - intraspp variation vs abs(latitude)

%% barplot that shows taxonomic coverage of the sampling
%% use different colors for each taxonomic group and shade to represent
%% percentage covered by samples



\section{Introduction}

Barcoding studies have typically two main goals: species discovery (how does the
barcoding data compare to the taxonomy?), and specimen identification (can the
barcode library be used to identify a species?) \cite{Collins2013}. In this
study we focus on describing the patterns of unrecognized diversity, and testing
the role of latitude and phylogeny in shaping these patterns.

* barcoding has limitations, but when used with comprehensive taxonomic and
geographic sampling, powerful to assess diversity, in particular in groups that
haven't received lots of taxonomic attention

* In such cases, barcoding has typically revealed more diversity than previously
acknowledged. From the variety of studies, clearly many different patterns
emerge. Using large datasets allow to evaluate the relative importance of these
patterns. Examples: differentiation between IO and PO, unrecognized endemics in
Red Sea, Hawaii

* On the other hand, barcoding has also revealed instances of clear
morphological differences with limited genetic differentiation. Three main
hypotheses to explain this pattern (hybridization, incomplete lineage sorting,
polymorphism). How common is this pattern? Are the same explanations always
behind these patterns?

* few groups have been sampled extensively. Diversity in IWP thought to follow
diversity patterns of more well-known species: mollusks, fish, corals. Most of
the diversity is in the coral triangle. However, other groups don't always seem
to follow this pattern (e.g., Calcinus). Comprehensive sampling allows to
revisit this question.

* Behind these patterns is rate of secondary sympatry, molecular data allows to
test whether diversification occurs mostly in allopatry or in sympatry. And
once, diversification has occurred how long it takes for species to co-exist in
sympatry.

* To assess time it takes, need a good molecular clock, however, in most marine
invertebrates not really possible because fossils are too limited. However,
there are several pairs of sister species across isthmus of Panama, so we can
evaluate differences in rates, and

* This study is on sea cucumbers because poor understanding of species limits
use of conservative characters used in species-level taxonomy. Yet need for
management and better understanding of biology given fisheries pressures.

* Presentation of the dataset: most geographically and taxonomically
comprehensive barcoding dataset.

* Goals:
  - assess amount of cryptic diversity
  - evaluate geographic patterns of diversity and diversification
  - re-evaluate molecular clock


\section{Materials and Methods}

\subsection{Specimen identification}

Most specimens were individually identified by GP, FM, Mark O'Loughlin and other
taxonomic specialists. For most group, survey of primary literature was used to
assign the most accurate names. This effort led to the re-discovery of taxonomic
names that have been forgotten/never used in the literature, and names were
resurrected from synonymies.

\subsection{Sequencing}

DNA was extracted according to one of the following three protocols: (1) DNAzol
followed by QIAGEN PCR clean up kit; (2) organic extractions at the Smithsonian
Institution using robotic facilities; (3) EZNA Mollusc kit.

We amplified the 5' end of COI using the echinoderm primers developed by
\cite{Hoareau2010}. The sequencing was performed at the Interdisciplinary Center
Biotechnology Research at the University of Florida. Chromatograms were
assembled and edited using Geneious 5.5.8 \cite{Geneious558}.

We kept all sequences that were more than 600 bp,

\subsection{Diversity}

% context: How much diversity in a group that hasn't received lots of
% taxonomic attention and with potential for high levels of cryptic diversity
% because of characters used to delineate species? and yet, relatively easy to
% sample

-  [discussion] use of thresholds: problem such large datasets, differences in rates of
molecular evolution making single threshold approach potentially challenging
- [results] show image that represent: differences in topologies,
(paraphyly/polyphyly), long branches
- [results] comparison of results from the 2 methods
- [discussion] does it really matter that ESUs identified aren't really species? they are
proxy for genetic diversity --> much higher than current understanding of
species limits

- [results] comparison with number of species from taxonomy
- [results] how much of the genera/families were sampled?
- [results] adequate sampling across the range of the species

The size of the dataset restricts the methods that can be used to assess
diversity within the dataset, and computationally intensive methods such as the
Generalized Mixed Yule Coalescent method \cite{Pons2006} cannot be used
here. Other programs cannot accommodate such large dataset, and failed to
complete the analysis. Therefore, we were here limited to use threshold-based
methods to estimate the number of species and used two approaches: pairwise
distances and the cluster identification method.

Based on pairwise distances, we grouped individuals that diverged at most by a
given threshold. This method is strictly based on the genetic distance and does
not take into account phylogenetic information.

We used here a new method that identifies monophyletic clusters of individuals
from a neighbor-joining tree (other tree reconstruction methods can be used),
reconstructed from the pairwise genetic distances. Individuals belonging to the
same cluster are separated by genetic distance less than a threshold set
\textit{a priori}. Since it is based on the maximum intraspecific distance, it
shares similarity with the local barcoding graphs, where maximum intra-specific
distance between individuals is plotted against the distance to the closest
neighboring species (see \cite[Fig.~4 in]{Robinson2009} for an example). It
differs as it only uses information from the tree (no need to associate species
names with the sequences), but suffers from the caveats associated with using
arbitrary thresholds.

For each of these two approaches, we used both uncorrected distances ($p$) and
the Kimura two-parameter (K2P) distance \cite{Kimura1980} to estimate pairwise
distances. The K2P distance is very widely used in barcoding studies, but a
recent study indicated that the $p$ distance is probably more appropriate when
comparing genetic distances between closely related species and may lead to
higher rates of identification success \cite{Collins2012}. We estimated the
number of species recovered from our sample while varying the pairwise threshold
value: \Sexpr{paste0(load_thresholdPairwise(), collapse=", ")}. Additionally, we
estimated the proportion of singletons (proportion of the number species
represented by a single individual) for each of these threshold values. If a
suitable threshold allows to detect the barcoding gap and therefore estimate
diversity within a group, we expect the number of species estimated to
stabilize. Similarly, we expect that the proportion of singletons decreases when
the threshold identifies the barcoding gap by going from overspliting.

We repeated these analyses on the entire dataset, on each order and each family.

\subsection{Geography, diversity and diversification}

We investigated the geographic patterns of diversity from the ESUs identified
from the barcoding data. For each ESUs, when three or more locations were
sampled, we computed the convex hull to obtain a polygon approximating their
distribution. To obtain a diversity contour map, we superimposed the polygons
obtained.

If dispersal is spatially restricted, a pattern of isolation-by-distance (IBD),
where genetic differentiation increases with geographical distance, may be
detected. In sea cucumbers, as with other marine invertebrate, dispersal
typically occurs during the larval stage. Larvae can be planktotrophic (they
feed in the plankton), or oligotrophic (they feed on reserves included with the
egg). A few species of sea cucumbers are also brooders and adults release
juveniles. The type of development and larvae may influence the dispersal
potential of the species, with brooders having little dispersal potential while
species with planktotrophic larvae might disperse over longer distances. To test
for evidence of IBD we investigated the relationship between the maximum
intra-ESU genetic distances and the maximum geographical distances sampled for
each ESUs represented by three or more individuals. While the reproductive
biology of most sea cucumber species has not been investigated, it is recognized
that most species of Aspidochirotida and Apodida have planktotrophic larvae,
while species of Dendrochirotida have oligotrophic larvae. To assess if these
differences in life history among the orders had an effect of the IBD pattern,
we analyzed them separately.

To test whether tropical and low-latitude species affected the IBD
pattern, we performed an ANCOVA on the maximum intra-ESU genetic distances as
the response variable, the maximum geographical distance for each ESU as the
covariate and the zone of occurrence as the independent variable (species for
which the absolute mean of their latitudinal range is < 23$^{\circ}$ were
classified as ``tropical'', others were classified as ``other''). We only had
enough data for the Dendrochirotida to do this analysis. For the other groups,
we compared the results obtained on the full dataset and on the dataset
restricted to the zone of occurrence with the most data (tropics for the
Aspidochirotida and Apodida; other for the Elasipodida). We did not have enough
data to analyze the Molpadida or the Dactylochirotida separately.

- Diversity:
  - [future] map of number of unique haplotypes per geographic areas
  - areas of high ``species'' richness
  - do species with large ranges have higher levels of genetic
  differentiation? (isolation by distance)

- Diversification:
  - Are sister species allopatric or sympatric?
  - role of geologic/geographic barriers
  - Where are the barriers to cladogenesis?
  - Is there signal that the timing of differentiation is similar for areas
  with high endemism? Hawaii? Red Sea?
  - Rates of secondary sympatry
  - amount of divergence among individuals found in sympatry
      (plot: %divergence vs. %sympatry(smaller ranged species))


\subsection{Molecular clock estimation}

- can we use isthmus of panama to calibrate the sea cucumber molecular clocks?
- differences in pairwise divergence for geminate species caused by:
- differences in timing: some species might have diverged before closure of
isthmus
- differences in rates of molecular evolution




\section{Results}

<<cluster-groups-data, cache=TRUE, >>=

@

<<pairwise-groups-data, cache=TRUE>>=

@

<<nGrps-groups-comparison-plot, cache=TRUE>>=

@

<<pSngl-groups-comparison-plot, cache=TRUE>>=

@


\subsection{Geography, diversity and diversification}

<<isolation-by-distance-data, cache=TRUE, results='hide'>>=
@

<<isolation-by-distance-plot, cache=TRUE, dependson='isolation-by-distance-data', results='hide', fig.scap='Genetic and geographic distances for each order', fig.cap='Maximum genetic distance according to the maximum geographic distance for species identified with the clustering approach with a threshold of 3\\%, represented by at least 3 individuals. Lines represent a simple linear regresion.'>>=
@

<<isolation-by-distance-stats, cache=TRUE, dependson='isolation-by-distance-data'>>=

@


\section{Discussion}


% tradeoff between many species 1 gene / multiple genes

%% Geographical scale
% see Bergsten+2012

%% Neutrality of the sequences?
% Are all protein sequences identical?
%

%% Diversification rates

%% Role of geography/latitude
% diversification rates
% intra- and interspecific genetic variation

%% Cladogenetic breaks

%% Error rates/Exceptions?
% oversplitting
% underspliting
% hybridization
% "Exceptions may give valuable insight into the mechanisms controlling
% variiance withing & among species" \cite{Stoeckle2014}

\pagebreak

\bibliographystyle{plos2009}
\bibliography{cuke-barcoding_nourl}

\end{document}