#!/bin/bash

#PBS -N impatiens_raxml
#PBS -o impraxml.out
#PBS -e impraxml.err
#PBS -m ae

#PBS -M francois.michonneau@gmail.com
#PBS -l nodes=1:ppn=8
#PBS -l pmem=1500mb
#PBS -r n
#PBS -l walltime=168:00:00

module load raxml/8.0.25

cd $PBS_O_WORKDIR

raxmlHPC-PTHREADS-SSE3 -s data/cukeBarcodes-flagAmb.phy -m GTRGAMMA -q data/cukeBarcodes-partition -T8 -f a -p 10101 -x 10101 -# 500 -n cukeBarcodes

echo Done;


