
load_tree_raxml <- function(raxml_tree_file,
                            cuke_db) {
    ## load the tree file generated by RAxML that contains the bootstrap support values
    tree <- ape::read.tree(file = raxml_tree_file)
    tree$tip.label <- make_labels_from_guids(cuke_db,
                                              tree$tip.label)
    tree
}

load_tree_phylo4 <- function(distance="raw", taxa="all") {
    distance <- match.arg(distance, c("raw", "K80"))
    if(identical(distance, "raw")) {
        tree <- load_cukeTree_raw_phylo4()
    }
    else {
        tree <- load_cukeTree_k2p_phylo4()
    }

    if (taxa == "all") {
        tree
    }
    else {
        toKeep <- fetch_guids_from_taxa(taxa)
        tree <- subset(tree, tips.include = toKeep)
        stopifnot(all(toKeep %in% tipLabels(tree)) ||
                  all(!is.na(toKeep)))
        tree
    }
}

load_tree_raxml_phylo4 <- function(raxml_tree, taxa="all") {
    tr <- phytools::midpoint.root(raxml_tree)
    tr <- as(tr, "phylo4")
    bs <- nodeLabels(tr)
    bs <- data.frame(bs, stringsAsFactors=FALSE)
    bs$bs <- as.numeric(bs$bs)
    tr <- phylo4d(tr, node.data=bs)
    tr <- removeNodeLabels(tr)

    if (taxa == "all") {
        invisible(tr)
    }
    else {
        to_keep <- fetch_guids_from_taxa(taxa)
        tr <- subset(tr, tips.include = to_keep)
        stopifnot(all(to_keep %in% tipLabels(tr)) ||
                  all(!is.na(to_keep)))
        invisible(tr)
    }
}


load_species_pairwiseGrps <- function(distance="raw", taxa="all",
                                      threshold=0.03) {

    taxonomyDf <- load_taxonomyDf()
    thres <- load_threshold_pairwise()

    taxa <- match.arg(as.character(taxa), taxonomyDf$taxa)
    distance <- match.arg(distance, c("raw", "K80"))
    stopifnot(length(threshold) == 1 && threshold %in% thres)

    pairwiseGrpRes <- load_pairwiseGrpRes()
    nmRes <- paste(distance, taxa, sep="-")
    res <- pairwiseGrpRes[[match(nmRes, names(pairwiseGrpRes))]][[which(thres == threshold)]]
    stopifnot(! is.null(res))
    res
}

load_tree_pairwiseGrps <- function(distance="raw", taxa="all",
                                   threshold=0.03) {
    spp <- load_species_pairwiseGrps(distance=distance, taxa=taxa,
                                     threshold=threshold)
    lSpp <- sapply(spp, length)
    tmpGrps <- mapply(rep, 1:length(lSpp), lSpp)
    tmpGrps <- data.frame(Groups=unlist(tmpGrps))
    rownames(tmpGrps) <- unlist(spp)

    tree <- load_tree_phylo4(distance=distance, taxa=taxa)
    addData(tree, tip.data=tmpGrps)
}



load_tree_manualGrps <- function(taxa="Holothuriidae", overwrite=FALSE) {
    fnm <- "data/cukeTree-manualESUs.rds"
    ##distance <- match.arg(distance, c("raw", "K80"))
    taxa <- match.arg(taxa) ## only Holothuriidae for now
    if (file.exists(fnm) && !overwrite) {
        manESU <- readRDS(file=fnm)
    }
    else {

        manESU <- load_manESU()
        tree <- load_tree_raxml_phylo4(taxa)
        tDat <- data.frame(as.numeric(factor(manESU$ESU_noGeo)))
        names(tDat) <- "Groups"
        rownames(tDat) <- manESU$Labels
        manESU <- addData(tree, tip.data=tDat)
        saveRDS(manESU, file=fnm)
    }
    invisible(manESU)
}
